<?php
error_reporting(E_ALL);
header("Content-type: text/html; charset=utf-8");
class Article{
    public $title;
    public $text;

    public function __construct($zagol, $text = 'Текст статьи')
    {
        $this->title = $zagol;
        $this->text = $text;
    }

    public function view(){
        echo '<h1>' . $this->title . '</h1>';
        echo '<div>' . $this->text . '</div>';
    }
}

class News extends Article {
    protected $autor;
    public function __construct($zagol = 'sdgfdfh', $text = 'gergrhjyjyt', $autor = 'sffggf')
    {
        parent::__construct($zagol, $text);
        $this->autor = $autor;
    }
    public function aut(){
        $this->autor = 'qwer';
    }
    public function view()
    {
        parent::view(); // TODO: Change the autogenerated stub
        echo '<sub>' . $this->autor . '</sub>';
    }
}
class NewNews extends News{
    const PI = 3.14159;
    static public $qwer = 'qwer';
    public function __construct($zagol, $text, $autor)
    {
        parent::__construct($zagol, $text, $autor);
    }
    public function aut1()
    {
        $this->autor = 'sfdgdfghfdghfghhfghfghfghfghfghfghfg';
    }
    public function aut2(){
        $this->aut();
    }
    public function view()
    {
        parent::view(); // TODO: Change the autogenerated stub
        echo self::$qwer;
    }
}
$art = new Article('новость');
//$art->title = 'важная новость';
//$art->text = 'текст важной новости.';
$art->view();

$newss = new News('qwqwweerrtrytyuyuiiu', 'dgfdbfgnbdfn trhrthrtrj rthjrhjt;yhltk');
$newss->view();
$newss->aut();
$newss->view();

$newnewss = new NewNews('dgfdgdfg', 'dgfhfhfgh', 'sgdgdhdtertertwetertretert');
$newnewss->view();
$newnewss->aut();
$newnewss->view();
echo $newnewss::PI;